"""initial_migration

Revision ID: d213f8e331d8
Revises: 
Create Date: 2026-07-17 19:55:28.679339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd213f8e331d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_checklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_checklist_nombre'), 'catalogo_checklist', ['nombre'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('vehiculos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patente', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('kilometraje_actual', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_ultimo_mantenimiento', sa.Date(), nullable=True),
    sa.Column('fecha_proximo_mantenimiento', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_patente'), 'vehiculos', ['patente'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_usuario_timestamp', 'audit_logs', ['usuario_id', 'timestamp'], unique=False)
    op.create_table('inspecciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehiculo_id', sa.Uuid(), nullable=False),
    sa.Column('coordinador_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('kilometraje', sa.Integer(), nullable=False),
    sa.Column('resultado_general', sa.String(length=20), nullable=False),
    sa.Column('mantenimiento_recomendado', sa.Text(), nullable=True),
    sa.Column('firma_url', sa.String(length=512), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coordinador_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inspeccion_vehiculo_fecha', 'inspecciones', ['vehiculo_id', 'fecha'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspeccion_id', sa.Uuid(), nullable=False),
    sa.Column('catalogo_id', sa.Uuid(), nullable=False),
    sa.Column('valor', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['catalogo_id'], ['catalogo_checklist.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspeccion_id'], ['inspecciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidencias_fotograficas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspeccion_id', sa.Uuid(), nullable=False),
    sa.Column('checklist_item_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspeccion_id'], ['inspecciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidencias_fotograficas')
    op.drop_table('checklist_items')
    op.drop_index('idx_inspeccion_vehiculo_fecha', table_name='inspecciones')
    op.drop_table('inspecciones')
    op.drop_index('idx_audit_log_usuario_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vehiculos_patente'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_catalogo_checklist_nombre'), table_name='catalogo_checklist')
    op.drop_table('catalogo_checklist')
    # ### end Alembic commands ###
